### ISSUE TITLE
"Show next pass" doesn't always show the next pass

### ISSUE THREAD

**Issue by Vinz87** [csete/gpredict#164] opened 2019-05-05 19:12 UTC
If I right-click on a satellite in whatever view and I select "show next pass", sometimes the pass selected in the pop-up view is not the next one but the subsequent one.
![Schermata 2019-05-05 alle 21 10 39](https://user-images.githubusercontent.com/6201178/57199011-51c3f200-6f7a-11e9-84be-6c57221fc29e.png)
![Schermata 2019-05-05 alle 21 10 19](https://user-images.githubusercontent.com/6201178/57199014-5c7e8700-6f7a-11e9-898a-08e7f290588b.png)

Other times it shows the actual next pass, the same listed in the previous view, as I think is the intended behaviour.

**Comment by csete** [comment] 2019-05-06 12:59
Hi,

Please note that when predicting passes, only passes that will have a minimum elevation above a certain threshold will be listed, see Preferences -> Predict -> Minimum elevation. This setting does not apply for "Next" in the real-time views. So I think this is just a duplicate of issue #75.

Also, in the future when reporting bugs, please make sure to include a thorough description of the environment, including which version of gpredict you are using and how it was installed.

**Comment by Vinz87** [comment] 2019-05-06 19:24
You're right, it was the "minimum elevation" which prevented the pass from being displayed.

**Comment by csete** [comment] 2019-05-06 19:45
Okay then, we will be fixing this in issue #75, so I am closing this one.

**Closed by csete** 2019-05-06 19:45 UTC
